name: 배포

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: pnpm 설정
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 의존성 캐싱
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: 의존성 설치
        run: pnpm install

      - name: 린트 검사
        run: pnpm lint

      - name: 타입 검사
        run: pnpm typecheck

      - name: 빌드
        run: pnpm build

      - name: Vercel CLI 설치
        run: pnpm add -g vercel

      - name: Vercel 배포
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Expo 배포 (선택사항)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd apps/expo
          npx eas-cli build --platform all --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
